name: Destruir Infraestructura AWS

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: main

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}

    steps:
      - name: Recuperar el código
        uses: actions/checkout@v5

      - name: Configurar las credenciales AWS
        run: |
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set aws_session_token "$AWS_SESSION_TOKEN"
          aws configure set region "$AWS_REGION"

      - name: Verificar las credenciales
        run: aws sts get-caller-identity

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.10.5

      - name: Inicializar Terraform
        run: terraform init -backend-config "bucket=${{ vars.BUCKET }}" -backend-config "dynamodb_table=${{ vars.LOCKS }}"
        working-directory: iac

      - name: Destruir infraestructura con Terraform
        run: |
          terraform destroy \
            -var="id_cuenta_aws=${{ vars.AWS_ACCOUNT_ID }}" \
            -var="nombre_rol_iam=${{ vars.NOMBRE_ROL_IAM }}" \
            -var="path_base_servicio=${{ vars.PATH_BASE_SERVICIO }}" \
            -var="nombre_cluster_ecs=${{ vars.NOMBRE_CLUSTER }}" \
            -var="familia_tarea_ecs=${{ vars.FAMILIA_TAREA_ECS }}" \
            -var="nombre_repo_ecr=${{ vars.NOMBRE_REPO_ECR }}" \
            -var="host_base_datos=${{ vars.HOST_BASE_DATOS }}" \
            -var="nombre_base_datos=${{ vars.NOMBRE_BASE_DATOS }}" \
            -var="usuario_base_datos=${{ vars.USUARIO_BASE_DATOS }}" \
            -var="contrasenha_base_datos=${{ secrets.CONTRASENHA_BASE_DATOS }}" \
            -var="nombre_servicio_ecs=${{ vars.NOMBRE_SERVICIO }}" \
            -auto-approve
        working-directory: iac
